from neurolab import params as P
import params as PP


config_1l = {
	P.KEY_EXPERIMENT: 'neurolab.experiment.VisionExperiment',
	P.KEY_NET_MODULES: 'models.gdes.model_1l.Net',
	P.KEY_NET_OUTPUTS: 'fc2',
	P.KEY_DATA_MANAGER: 'neurolab.data.CIFAR10DataManager',
	P.KEY_AUGMENT_MANAGER: None, #'neurolab.data.LightCustomAugmentManager',
	P.KEY_AUGM_STAT_PASSES: 2,
	P.KEY_AUGM_BEFORE_STATS: True,
	P.KEY_WHITEN: None,
	P.KEY_TOT_TRN_SAMPLES: 40000,
	P.KEY_BATCHSIZE: 64,
	P.KEY_INPUT_SHAPE: (3, 32, 32),
	P.KEY_NUM_EPOCHS: 20, #40,
	P.KEY_OPTIM_MANAGER: 'neurolab.optimization.optim.SGDOptimManager',
	P.KEY_SCHED_MANAGER: 'neurolab.optimization.sched.MultiStepSchedManager',
	P.KEY_LOSS_METRIC_MANAGER: 'neurolab.optimization.metric.CrossEntMetricManager',
	P.KEY_CRIT_METRIC_MANAGER: 'neurolab.optimization.metric.AccMetricManager',
    P.KEY_LEARNING_RATE: 1e-3,
    P.KEY_LR_DECAY: 0.5, # 0.1,
    P.KEY_MILESTONES: range(10, 20), # [20, 30],
    P.KEY_MOMENTUM: 0.9,
    P.KEY_L2_PENALTY: 5e-2,
	P.KEY_DROPOUT_P: 0.5,
}

config_1l_hebb = {
	P.KEY_EXPERIMENT: 'neurolab.experiment.VisionExperiment',
	P.KEY_NET_MODULES: 'models.hebb.model_1l.Net',
	P.KEY_NET_OUTPUTS: 'fc2',
	P.KEY_DATA_MANAGER: 'neurolab.data.CIFAR10DataManager',
	P.KEY_AUGMENT_MANAGER: None, #'neurolab.data.LightCustomAugmentManager',
	P.KEY_AUGM_STAT_PASSES: 2,
	P.KEY_AUGM_BEFORE_STATS: True,
	P.KEY_WHITEN: 2,
	P.KEY_TOT_TRN_SAMPLES: 40000,
	P.KEY_BATCHSIZE: 64,
	P.KEY_INPUT_SHAPE: (3, 32, 32),
	P.KEY_NUM_EPOCHS: 20,
	P.KEY_OPTIM_MANAGER: 'neurolab.optimization.optim.SGDOptimManager',
	P.KEY_CRIT_METRIC_MANAGER: 'neurolab.optimization.metric.AccMetricManager',
    P.KEY_LEARNING_RATE: 1e-3,
	P.KEY_LOCAL_LRN_RULE: 'hwta',
	PP.KEY_WTA_K: 1,
}

config_vae = {
	P.KEY_EXPERIMENT: 'neurolab.experiment.AEVisionExperiment',
	P.KEY_NET_MODULES: 'models.gdes.vae_6l.Net',
	P.KEY_NET_OUTPUTS: 'vae_output',
	P.KEY_DATA_MANAGER: 'neurolab.data.CIFAR10DataManager',
	P.KEY_AUGMENT_MANAGER: None, #'neurolab.data.LightCustomAugmentManager',
	P.KEY_AUGM_STAT_PASSES: 2,
	P.KEY_AUGM_BEFORE_STATS: True,
	P.KEY_WHITEN: None,
	P.KEY_TOT_TRN_SAMPLES: 40000,
	P.KEY_BATCHSIZE: 64,
	P.KEY_INPUT_SHAPE: (3, 32, 32),
	P.KEY_NUM_EPOCHS: 20, #40,
	P.KEY_OPTIM_MANAGER: 'neurolab.optimization.optim.SGDOptimManager',
	P.KEY_SCHED_MANAGER: 'neurolab.optimization.sched.MultiStepSchedManager',
	P.KEY_LOSS_METRIC_MANAGER: 'neurolab.optimization.metric.ELBOMetricManager',
	P.KEY_CRIT_METRIC_MANAGER: 'neurolab.optimization.metric.ELBOMetricManager',
    P.KEY_LEARNING_RATE: 1e-3,
    P.KEY_LR_DECAY: 0.5, #0.1,
    P.KEY_MILESTONES: range(10, 20), #[20, 30],
    P.KEY_MOMENTUM: 0.9,
	P.KEY_ELBO_BETA: .5,
}

fc_on_gdes_layer = {
	P.KEY_EXPERIMENT: 'neurolab.experiment.VisionExperiment',
	P.KEY_NET_MODULES: 'models.gdes.fc.Net',
	P.KEY_NET_OUTPUTS: 'fc',
	P.KEY_DATA_MANAGER: 'neurolab.data.CIFAR10DataManager',
	P.KEY_AUGMENT_MANAGER: None, #'neurolab.data.LightCustomAugmentManager',
	P.KEY_AUGM_STAT_PASSES: 2,
	P.KEY_AUGM_BEFORE_STATS: True,
	P.KEY_WHITEN: None,
	P.KEY_TOT_TRN_SAMPLES: 40000,
	P.KEY_BATCHSIZE: 64,
	P.KEY_INPUT_SHAPE: (3, 32, 32),
	P.KEY_NUM_EPOCHS: 20, #40,
	P.KEY_OPTIM_MANAGER: 'neurolab.optimization.optim.SGDOptimManager',
	P.KEY_SCHED_MANAGER: 'neurolab.optimization.sched.MultiStepSchedManager',
	P.KEY_LOSS_METRIC_MANAGER: 'neurolab.optimization.metric.CrossEntMetricManager',
	P.KEY_CRIT_METRIC_MANAGER: 'neurolab.optimization.metric.AccMetricManager',
    P.KEY_LEARNING_RATE: 1e-3,
    P.KEY_LR_DECAY: 0.5, #0.1,
    P.KEY_MILESTONES: range(10, 20), #[20, 30],
    P.KEY_MOMENTUM: 0.9,
    P.KEY_L2_PENALTY: 5e-4,
	P.KEY_DROPOUT_P: 0.5,
	P.KEY_PRE_NET_MODULES: ['models.gdes.model_1l.Net'],
	P.KEY_PRE_NET_MDL_PATHS: [P.PROJECT_ROOT + '/results/configs/base/config_1l/iter_' + P.STR_TOKEN + '/models/model0.pt'],
	P.KEY_PRE_NET_OUTPUTS: ['bn1'],
}

fc_on_hebb_layer = {
	P.KEY_EXPERIMENT: 'neurolab.experiment.VisionExperiment',
	P.KEY_NET_MODULES: 'models.gdes.fc.Net',
	P.KEY_NET_OUTPUTS: 'fc',
	P.KEY_DATA_MANAGER: 'neurolab.data.CIFAR10DataManager',
	P.KEY_AUGMENT_MANAGER: None, #'neurolab.data.LightCustomAugmentManager',
	P.KEY_AUGM_STAT_PASSES: 2,
	P.KEY_AUGM_BEFORE_STATS: True,
	P.KEY_WHITEN: 2,
	P.KEY_TOT_TRN_SAMPLES: 40000,
	P.KEY_BATCHSIZE: 64,
	P.KEY_INPUT_SHAPE: (3, 32, 32),
	P.KEY_NUM_EPOCHS: 20, #40,
	P.KEY_OPTIM_MANAGER: 'neurolab.optimization.optim.SGDOptimManager',
	P.KEY_SCHED_MANAGER: 'neurolab.optimization.sched.MultiStepSchedManager',
	P.KEY_LOSS_METRIC_MANAGER: 'neurolab.optimization.metric.CrossEntMetricManager',
	P.KEY_CRIT_METRIC_MANAGER: 'neurolab.optimization.metric.AccMetricManager',
    P.KEY_LEARNING_RATE: 1e-3,
    P.KEY_LR_DECAY: 0.5, #0.1,
    P.KEY_MILESTONES: range(10, 20), #[20, 30],
    P.KEY_MOMENTUM: 0.9,
    P.KEY_L2_PENALTY: 5e-4,
	P.KEY_DROPOUT_P: 0.5,
	P.KEY_LOCAL_LRN_RULE: 'hwta',
	PP.KEY_WTA_K: 1,
	P.KEY_PRE_NET_MODULES: ['models.hebb.model_1l.Net'],
	P.KEY_PRE_NET_MDL_PATHS: [P.PROJECT_ROOT + '/results/configs/base/config_1l_hebb/iter_' + P.STR_TOKEN + '/models/model0.pt'],
	P.KEY_PRE_NET_OUTPUTS: ['bn1'],
}

sk_on_gdes_layer = {
	P.KEY_EXPERIMENT: 'neurolab.experiment.VisionExperiment',
	P.KEY_NET_MODULES: 'neurolab.model.skclassif.KNNClassifier',
	P.KEY_NET_OUTPUTS: 'clf',
	P.KEY_DATA_MANAGER: 'neurolab.data.CIFAR10DataManager',
	P.KEY_AUGMENT_MANAGER: None, #'neurolab.data.LightCustomAugmentManager',
	P.KEY_AUGM_STAT_PASSES: 2,
	P.KEY_AUGM_BEFORE_STATS: True,
	P.KEY_WHITEN: None,
	P.KEY_TOT_TRN_SAMPLES: 40000,
	P.KEY_BATCHSIZE: 64,
	P.KEY_INPUT_SHAPE: (3, 32, 32),
	P.KEY_NUM_EPOCHS: 1, #2,
	P.KEY_CRIT_METRIC_MANAGER: 'neurolab.optimization.metric.AccMetricManager',
	P.KEY_SKCLF_NUM_SAMPLES: 40000, #80000,
	P.KEY_NYSTROEM_N_COMPONENTS: 100,
	P.KEY_KNN_N_NEIGHBORS: 10,
	P.KEY_PRE_NET_MODULES: ['models.gdes.model_1l.Net'],
	P.KEY_PRE_NET_MDL_PATHS: [P.PROJECT_ROOT + '/results/configs/base/config_1l/iter_' + P.STR_TOKEN + '/models/model0.pt'],
	P.KEY_PRE_NET_OUTPUTS: ['bn1'],
}

multiexp_fc_on_gdes_layer = {
	P.KEY_EXPERIMENT: 'neurolab.experiment.multiexp.MultiExperiment',
	P.KEY_SUBCONFIG_LIST: ['configs.base.config_1l', 'configs.base.fc_on_gdes_layer'],
	'exp0+exp1:' + P.KEY_NUM_EPOCHS: 2,
	'exp0+exp1:' + P.KEY_LEARNING_RATE: 1e-3,
	'exp0:' + P.KEY_L2_PENALTY: 5e-2,
	'exp1:' + P.KEY_L2_PENALTY: 5e-4,
	'exp1:' + P.KEY_PRE_NET_MDL_PATHS: ['exp0/iter_' + P.STR_TOKEN + '/models/model0.pt'],
	P.KEY_HPMANAGER: 'neurolab.hpsearch.DiscAltMinHPManager',
	P.KEY_HPSEARCH_PARAMS: {'exp0+exp1:' + P.KEY_LEARNING_RATE: [1e-4, 1e-3], 'exp0:' + P.KEY_L2_PENALTY: [5e-2, 5e-3, 5e-4], 'exp1:' + P.KEY_L2_PENALTY: [5e-2, 5e-3, 5e-4]},
}
	
